08-rails/solar_system/config/routes.rb
Rails.application.routes.draw do
  root to: 'planets#index'
  get '/planets' => 'planets#index' #planet_path
  get 'planets/new' => 'planets#new'
  post '/planets' => 'planets#create' # implicitly planets path
  get 'planets/:id' => 'planets#show', :as => 'planet' # planet_path
  get '/planets/:id/edit' => 'planets#edit', :as => 'planets_edit'
  post '/planets/:id' => 'planets#update'
  delete '/planets/:id' => 'planets#destroy'
end

08-rails/solar_system/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id       :integer          primary key
#  name     :text
#  image    :text
#  orbit    :float
#  diameter :float
#  mass     :float
#  moons    :integer
#

class Planet < ActiveRecord::Base

end

08-rails/solar_system/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def show
    @planet = Planet.find params[:id]

  end

  def new
  end

  def create
    planet = Planet.create planet_params
    redirect_to planet_path(planet.id)
  end

  def destroy
    planet = Planet.find params[:id]
    planet.destroy
    redirect_to planets_path
  end

  def edit
    @planet = Planet.find params[:id]
  end

  def update
    planet = Planet.find params[:id]
    planet.update planet_params
    redirect_to planet_path(planet.id)
  end

  private
  # return safe set of parameters (with anything bad removed)

  def planet_params #strong params
    # whitelist
    params.require(:planet).permit(:name, :image, :orbit, :diameter, :mass, :moons)
  end
end

08-rails/solar_system/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>SolarSystem</title>
    <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
    <nav>
        <%= link_to 'All Planets', planets_path %>
        <%= link_to 'New Planet', planets_new_path %>
    </nav>
    <%= yield %>
</div>
</body>
</html>