08-rails/moma/config/routes.rb
# == Route Map
#
#      Prefix Verb   URI Pattern                 Controller#Action
# works_index GET    /works/index(.:format)      works#index
#   works_new GET    /works/new(.:format)        works#new
#  works_edit GET    /works/edit(.:format)       works#edit
#  works_show GET    /works/show(.:format)       works#show
#     artists GET    /artists(.:format)          artists#index
#             POST   /artists(.:format)          artists#create
#  new_artist GET    /artists/new(.:format)      artists#new
# edit_artist GET    /artists/:id/edit(.:format) artists#edit
#      artist GET    /artists/:id(.:format)      artists#show
#             PATCH  /artists/:id(.:format)      artists#update
#             PUT    /artists/:id(.:format)      artists#update
#             DELETE /artists/:id(.:format)      artists#destroy
#       works GET    /works(.:format)            works#index
#             POST   /works(.:format)            works#create
#    new_work GET    /works/new(.:format)        works#new
#   edit_work GET    /works/:id/edit(.:format)   works#edit
#        work GET    /works/:id(.:format)        works#show
#             PATCH  /works/:id(.:format)        works#update
#             PUT    /works/:id(.:format)        works#update
#             DELETE /works/:id(.:format)        works#destroy
# 

Rails.application.routes.draw do
  root to: 'works#index'
  resources :artists
  resources :works

end

08-rails/moma/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :text
#  nationality :text
#  dob         :date
#  period      :text
#  image       :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  has_many :works
end

08-rails/moma/app/models/work.rb
# == Schema Information
#
# Table name: works
#
#  id         :integer          not null, primary key
#  title      :text
#  year       :text
#  medium     :text
#  style      :text
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#

class Work < ActiveRecord::Base
  belongs_to :artist, optional: true
end

08-rails/moma/app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create artist_params
    redirect_to artist # /artists/:some_id i.e. the show page
  end

  def edit
    @artist = Artist.find params[:id]
  end

  def update
    artist = Artist.find params[:id]
    artist.update artist_params
    redirect_to artist
  end

  def show
    @artist = Artist.find params[:id]
  end

  def destroy
    artist = Artist.find params[:id]
    artist.destroy
    redirect_to artists_path
  end

  # Strong params: a whitelist of permitted fields
  private
  def artist_params
    params.require(:artist).permit(:name, :nationality, :dob, :period, :image)
  end
end

08-rails/moma/app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
    @works = Work.all.order(:created_at) # or just Work.all.order
  end

  def new
    @work = Work.new
  end

  def create
    work = Work.create work_params
    redirect_to work
  end

  def edit
    @work = Work.find params[:id]

  end

  def update
    work = Work.find params[:id]
    work.update work_params
    redirect_to work
  end

  def show
    @work = Work.find params[:id]
  end

  def destroy
    work = Work.find params[:id]
    work.destroy
    redirect_to works_path
  end


  # Strong params: a whitelist of permitted fields
  private
  def work_params
    params.require(:work).permit(:title, :year, :medium, :style, :image, :artist_id)
  end
end

08-rails/moma/app/helpers/artists_controller_helper.rb
module ArtistsControllerHelper
end

08-rails/moma/app/helpers/artists_helper.rb
module ArtistsHelper
end

08-rails/moma/app/helpers/works_helper.rb
module WorksHelper
end

08-rails/moma/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Moma</title>
    <%= csrf_meta_tags %>
    <!-- Compressed CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/css/foundation.min.css" integrity="sha256-itWEYdFWzZPBG78bJOOiQIn06QCgN/F0wMDcC4nOhxY=" crossorigin="anonymous" />

    <!-- Compressed JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.4.3/js/foundation.min.js" integrity="sha256-Nd2xznOkrE9HkrAMi4xWy/hXkQraXioBg9iYsBrcFrs=" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<div class="container">
    <nav>
        <%= link_to 'All Artists', artists_path %>
        <%= link_to 'New Artist', new_artist_path %>
        |
        <%= link_to 'All Works', works_path %>
        <%= link_to 'New Work', new_work_path %>
    </nav>
    <%= yield %>
</div>
</body>
</html>